highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://AkshayKishore.me/vitae
author: Me

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Akshay's Resume
name: Akshay
email: akshayvicky96@gmail.com
email_full: mailto:akshayvicky96@gmail.com
website: github.io/AkshayKishore
website_full: https://AkshayKishore.github.io/AkshayKishore
github: AkshayKishore
# twitter: twitter
#tel: +44 0000 000000
tel_full: tel:+91 960721840
#google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
address: 4/43 shanmugha nagar,Trichy
postcode: 620102
city: Trichirapalli
country: India
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
